#!/bin/bash

# THIS IS TO BE RUN INSIDE THE DOCKER CONTAINER, INITIATED BY THE picocmd SCRIPT
# DO NOT RUN THIS MANUALLY, ESPECIALLY DO NOT RUN IT IN THE HOST ENVIRONMENT.

set -euo pipefail

if ! (( $# )); then
	if (( "${verbose:-0}" )); then
		set -- /usr/bin/mono /opt/picoscope/lib/PicoScope.GTK.exe
	else
		set -- /opt/picoscope/bin/picoscope
	fi
fi

if [ -n "${hostname:-}" ]; then
	echo "127.0.0.1 $hostname" >> /etc/hosts
fi

exec env \
	DISPLAY="$DISPLAY" \
	XDG_RUNTIME_DIR="$XDG_RUNTIME_DIR" \
	MONO_PATH=/opt/picoscope/lib \
	"$@"
